// Executable reference paths for the original lessons.
export const legacySolutions: Record<string, string[]> = {
  'level-1-1': ['git init'],
  'level-1-2': ['touch README.md'],
  'level-1-3': ['git status'],
  'level-1-4': ['git add README.md'],
  'level-1-5': ['git commit -m "First commit"'],
  'level-1-6': ['git log'],
  'level-1-7': ['echo "Hello Git" > README.md'],
  'level-1-8': ['git diff'],
  'level-1-9': ['git add README.md', 'git commit -m "Update README"'],
  'level-1-10': ['touch app.ts', 'git add app.ts', 'git commit -m "Add app.ts"'],
  'level-2-1': ['git branch feature'],
  'level-2-2': ['git switch feature'],
  'level-2-3': ['touch feature.txt'],
  'level-2-4': ['git add feature.txt', 'git commit -m "Add feature"'],
  'level-2-5': ['git switch main'],
  'level-2-6': ['ls'],
  'level-2-7': ['touch main.txt'],
  'level-2-8': ['git add main.txt', 'git commit -m "Add main.txt"'],
  'level-2-9': ['git log'],
  'level-3-1': ['git switch main'],
  'level-3-2': ['git merge feature'],
  'level-3-3': ['git switch -c feature2', 'touch feature2.txt', 'git add feature2.txt', 'git commit -m "Add feature2"'],
  'level-3-4': ['git switch main', 'touch main-update.txt', 'git add main-update.txt', 'git commit -m "Update main"'],
  'level-3-5': ['git merge feature2'],
  'level-4-1': ['git status'],
  'level-4-2': ['git stash'],
  'level-4-3': ['git stash list'],
  'level-4-4': ['git stash pop'],
  'level-5-1': ['git log'],
  'level-5-2': ['git reset --soft HEAD~1'],
  'level-5-3': ['git restore --staged error.txt', 'rm error.txt', 'echo "v2" > file.txt', 'git add file.txt', 'git commit -m "Correct commit"'],
  'level-5-4': ['git reset --hard HEAD~1'],
  'level-6-1': ['git log'],
  'level-6-2': ['git checkout c1'],
  'level-6-3': ['git switch main'],
  'level-7-1': ['git merge feature'],
  'level-7-2': ['git status'],
  'level-7-3': ['echo "<html>\n<body>\n<h1>Hello World</h1>\n</body>\n</html>" > index.html'],
  'level-7-4': ['git add index.html', 'git commit -m "Merge feature"']
};
