/** Editorial notes are authored per lesson; goal predicates remain the grading authority. */
export interface LessonNote { concept: string; verify: string; caution: string }
const note = (concept: string, verify: string, caution: string): LessonNote => ({ concept, verify, caution });
export const lessonNotes: Record<string, LessonNote> = {
  'operation-rebase-continue': note('載せ替えが競合で停止したら、app.tsの結果をResolvedに決めてから次へ進めます。', '解消内容をstageし、featureの親がc2で進行中の操作がなくなることを確認します。', 'ファイルを書き換えるだけでは続行できません。実Gitのrebase中はours/theirsの意味も確認します。'),
  'operation-rebase-abort': note('載せ替えを取りやめ、開始前のfeatureと作業内容へ戻します。', 'rebaseを中断する操作を成功させ、HEADがc3、app.tsがfeature versionへ戻ることを確認します。', 'abortとskipは別です。skipは現在の変更を外して後の変更へ進みます。'),
  'operation-pick-continue': note('移植する変更とmainの編集が競合しています。app.tsをResolvedに決めて移植を終えます。', 'stage後に続行し、Featureの記録と親c2、操作の終了を確認します。', 'cherry-pickの続行にはcherry-pickの操作を使います。別の履歴操作の続行とは交換できません。'),
  'operation-pick-abort': note('競合した移植を中断して、mainの変更を開始前へ戻します。', '中断操作の成功、HEADのc2、app.tsのmain versionを確認します。', '元の履歴を戻すことと、解消して新しい記録を作ることは別の復旧方法です。'),
  'operation-revert-continue': note('逆向きの変更が後続の編集と競合しています。取り消したい結果をbaseとして決めます。', '解消してstageした後、親c4の取り消しコミットと操作終了を確認します。', 'revertも競合します。履歴を消さず、必要な内容を残す取り消しを作ります。'),
  'operation-revert-abort': note('今回の取り消しを中断し、後続の編集later versionを残した元の状態へ戻します。', '中断操作、HEADのc4、app.tsのlater versionを確認します。', 'abortは今回のrevertを取りやめます。既に成功した過去のrevertを取り消す操作ではありません。'),
  'stash-tracked': note('追跡中のapp.tsだけを退避し、未追跡notes.txtを手元に残します。', 'stashが一件、app.tsがbase、notes.txtがmemoであることを確認します。', '通常のstashは未追跡を含みません。保存範囲を確認します。'),
  'stash-untracked': note('app.tsの編集と未追跡notes.txtを、同じ一時保管へまとめます。', 'stashが一件で、app.tsがbase、notes.txtが作業場所からなくなることを確認します。', '-uは未追跡を含めますがignore対象は含めません。このアプリもその境界を扱います。'),
  'stash-apply': note('stashのdraftを作業場所へ戻し、保管を残して結果を確認します。', 'app.tsがdraftで、stashが一件残ることを確認します。', 'applyは保管を削除しません。複数回適用すると競合する場合があります。'),
  'stash-pop': note('draftを復元し、適用できた保管を一覧から取り除きます。', 'app.tsがdraft、stashが零件であることを確認します。', 'popが競合すると保管は残ります。成功した復元と失敗した復元を区別します。'),
  'stash-select': note('最新ではなく、古いstash@{1}のdraftを選び、二件の保管を残します。', 'app.tsがdraftで、stashの件数が二件のままであることを確認します。', 'stashの番号は新しい保管や削除で変わります。適用前に対象を確認します。'),
  'stash-drop': note('不要な保管を削除し、作業ファイルへは適用しません。', 'stashが零件、app.tsがbaseのままであることを確認します。', 'dropした内容の復旧を保証しません。保管内容が不要かを先に確認します。'),
  'stash-conflict': note('main更新後の復元は競合します。保管を残し、必要な内容をCombinedへ解消してstageします。', 'app.tsがCombined、HEADがc2、stashが一件残り、git statusのUnmerged pathsがなくなることを確認します。', '内容を編集するだけでは未解消パスは残ります。git addで解消を記録し、復元結果を読んでから保管を削除します。'),
  'interactive-squash': note('Docsの変更とメッセージをFeatureへまとめ、一つの記録として残します。', '二つの内容を保ち、親c1とFeature・Docs両方のメッセージを確認します。', 'todoは画面またはsimulateで編集します。実Gitはエディタを使い、まとめるメッセージも編集できます。'),
  'interactive-fixup': note('Docsの内容をFeatureにまとめ、メッセージはFeatureだけを残します。', '両ファイルの内容と、親c1、メッセージFeatureを確認します。', 'squashとfixupは残すメッセージが違います。共有済み履歴の書き換えは合意が必要です。'),
  'interactive-reword': note('内容と順序を保ちながら、Featureの説明だけをImprove appへ変えます。', '履歴のDocs、Improve app、Initialという順と、両ファイルの内容を確認します。', 'このアプリのrewordは一時停止後にamendします。実Gitではメッセージ用エディタが開きます。'),
  'interactive-reorder': note('独立した文書変更を先へ移し、その後にアプリ変更を記録します。', '古い順ではDocsからFeatureへ進み、両方の内容が残ることを確認します。', '順序を変えると変更の依存関係によって競合します。任意の並べ替えが成功するわけではありません。'),
  'interactive-drop': note('Featureを履歴から外し、Docsだけをc1の後へ残します。', 'app.tsがversion 1へ戻り、文書とDocsのメッセージが残ることを確認します。', 'dropはその変更を適用しません。後のコミットが依存していると競合する場合があります。'),
  'interactive-split': note('editで止め、まとめた記録を作業内容として戻し、AppとDocsを別々に選んで記録します。', 'Docs、App、Initialという履歴と、途中のAppに文書変更を混ぜていないことを確認します。', 'mixed resetは編集内容を残します。続行前に必要な記録を作り、追跡ファイルをクリーンにします。'),
  'advanced-bisect-start': note('正常と異常の境界を、履歴の候補を試しながら絞り込む調査を開始します。', '操作案内にbisectの調査中と表示されることを確認します。', 'この模擬調査は主に第一親の直線履歴です。実Gitの複雑な履歴全体を再現しません。'),
  'advanced-bisect-candidate': note('既知の異常c5と正常c1を境界にすると、中間の候補c3を検証できます。', 'bisect中でHEADがc3になり、候補ファイルを読めることを確認します。', 'good/badは実際に検証した結果を指定します。名前から推測して判定する手順ではありません。'),
  'advanced-bisect-find': note('候補のファイルにあるgood/badを読み、異常が最初に入ったコミットを絞ります。', '候補ごとのapp.tsを読み、最終的に原因c3と表示されることを確認します。', '模擬課題はファイル内の目印で検証します。実務では再現手順やテストで良否を判断します。'),
  'advanced-bisect-reset': note('原因を見つけた後、調査を終了して元のmainの作業へ戻します。', '原因c3の記録、bisect終了、mainのc5への復帰を確認します。', '原因を特定しただけでは作業先は戻りません。調査の終了操作が必要です。'),
  'advanced-worktree-add': note('mainのdraftを残したまま、別の作業場所にhotfixを用意します。', '仮想worktreeのhotfixと、元のmainのdraftが両方残ることを確認します。', '実ディスクには作成しません。実Gitのworktreeは履歴を共有し、作業ツリーとindexを別々に持ちます。'),
  'advanced-worktree-fix': note('別worktreeのhotfixで修正し、mainの未コミットdraftを保護します。', 'hotfixのapp.tsがFixed、mainがc1、元の作業場所にdraftが残ることを確認します。', '仮想のcdで作業先を移します。履歴を共有することと、作業ファイルを共有することは別です。'),
  'advanced-worktree-remove': note('不要な作業場所だけを削除し、hotfixブランチの履歴は残します。', '仮想worktreeがなくなり、hotfixがc1を指すことを確認します。', 'worktree削除とブランチ削除は別です。実務では未記録の変更がないことを先に確認します。'),
  'advanced-sparse': note('展開範囲をsrcに限定しても、testsの記録を履歴から消す必要はありません。', 'srcとルートREADMEが作業場所にあり、testsは非表示でもHEADに残ることを確認します。', 'このアプリは基本的なcone形式を模擬します。非表示の追跡ファイルを削除と混同しないでください。'),
  'advanced-sparse-disable': note('展開範囲の限定を解除し、履歴にあるtestsも作業場所へ戻します。', 'sparse設定が解除され、README、src、testsがクリーンに展開されることを確認します。', '表示範囲を広げる操作であり、新しいファイルをコミットする操作ではありません。'),
  'advanced-submodule-add': note('依存リポジトリの特定コミットを、親の履歴へ参照として記録します。', 'vendor/libが初期化され、親のコミットにdep1への参照があることを確認します。', 'このアプリは参照を文字列として模擬します。実Gitはgitlinkと.gitmodulesを使い、別リポジトリを管理します。'),
  'advanced-submodule-init': note('親に記録されたdep1の参照から、依存側の作業内容を初期化します。', 'vendor/libのdep1と初期化済み状態を確認します。', 'update --initは通常、親が指定したコミットを取得します。依存側の最新を自動で採用する目的ではありません。'),
  'advanced-submodule-update': note('依存側をdep2へ更新した後、その参照変更を親でも記録します。', 'submoduleがdep2で、HEADのvendor/libにもdep2が記録されることを確認します。', '依存側の更新だけでは親のコミットは変わりません。参照をadd・commitする必要があります。'),
  'advanced-lfs-install': note('大きなファイルをLFSで扱うための設定を有効にします。', '模擬LFSの初期化が有効になったことを確認します。', '設定のみの演習です。実際のバイナリ転送やポインタ変換は行いません。'),
  'advanced-lfs-track': note('PNGをLFS対象とする属性ルールを.gitattributesへ記録し共有します。', 'LFSの初期化、*.pngのルール、HEADの.gitattributesを確認します。', 'この模擬環境は属性設定だけを扱います。実Git LFSのポインタとバイナリ転送は別に必要です。'),
  'precision-patch': note('app.tsのfeature変更だけを選び、logging変更は作業中として残します。', 'HEADではfeature=on・logging=off、作業ツリーではlogging=onであることを確認します。', 'add -pのy/n/qは提示中のハンクに対する応答です。実Gitには追加の対話選択肢もあります。'),
  'precision-ignore': note('生成物を作業場所に残し、管理するルールだけを履歴へ記録します。', 'HEADに.gitignoreがありbuild/output.txtがなく、作業ファイルは残ることを確認します。', 'ignoreは未追跡ファイルの選択を抑制します。既に追跡済みのファイルは別に追跡を外します。'),
  'precision-untrack': note('debug.logをindexから外し、今後の追加対象からも除外しつつ作業ファイルを残します。', 'HEADに*.logのルールがあり、debug.logは履歴になく手元に残ることを確認します。', 'rm --cachedは作業ファイルを消しません。ignoreを書くだけでは追跡をやめません。'),
  'precision-blame': note('ファイルの各行を最後に変更したコミットから、変更理由の調査を始めます。', 'app.tsの行ごとのIDとメッセージを読みます。', 'この模擬環境は一本の親履歴を追います。実Gitの移動・コピー検出等をすべて再現しません。'),
  'precision-diff-commits': note('作業ファイルを切り替えず、c1とc3に記録されたapp.tsを比較します。', '古い版から新しい版への追加・削除行を読みます。', '比較する二つの参照の順を逆にすると、追加と削除も逆になります。'),
  'precision-log-file': note('履歴の中からapp.tsに変更がある記録だけを読むことで、調査範囲を絞ります。', '対象パスに変更のあるコミットのメッセージと順を確認します。', '--の後はパスとして指定します。この模擬環境の履歴探索は主に第一親です。'),
  'precision-log-grep': note('メッセージのFeatureを手掛かりに、変更理由から履歴を探します。', 'Featureを含むコミットが表示されることを確認します。', 'メッセージ検索とファイル内容の検索は別です。この課題は模擬のメッセージ検索を扱います。'),
  'precision-lease': note('force-with-leaseの拒否は、想定した共有先と実際の位置が違うという警告です。', 'fetch後の変更を読み、双方の内容が手元とサーバーへ残ることを確認します。', 'fetchしてから機械的に強制pushする手順ではありません。更新の内容を判断して通常の統合をします。'),
  'precision-tag-push': note('タグの参照と必要な履歴を共有し、mainの公開位置は動かしません。', '公開v1.0.0がローカルmainを指し、サーバーのmainはc1のままであることを確認します。', '通常のブランチpushでタグもすべて送られるわけではありません。対象を指定します。'),
  'workflow-feature': note('機能の履歴をブランチで作り、公開してPRの確認を経てmainへ取り込みます。', 'PRの最新レビュー・CIと、統合先mainのfeature.txtを確認します。', 'simulateは模擬確認です。実務では変更の説明、テスト結果、レビュー内容を確認します。'),
  'workflow-conflict': note('push拒否とmerge競合を順に解決し、双方の履歴を保った結果を共有します。', 'Combinedの内容と二つの親、手元・サーバー双方の状態を確認します。', '競合による停止は途中状態です。この総合課題は解消と共有までを採点します。'),
  'workflow-urgent': note('作業中のfeatureを退避し、hotfixをmainへ統合してからfeatureへも移植します。', 'mainとfeatureのFixed、復元したWorking、空のstashを確認します。', '統合・移植・作業復元は別の段階です。退避内容を誤ったブランチへ戻さないよう確認します。'),
  'workflow-cleanup': note('不要な試行を外して履歴をまとめ、最新mainへ載せ替える際の文書競合を解消します。', 'FeatureとTeam docsの順、Combined docs、notes.mdのKeepと操作終了を確認します。', 'fixupとrebaseでIDが変わります。共有前の整理として使い、必要な文書を消さないよう確認します。'),
  'workflow-recovery': note('消したブランチのコミットをreflogから見つけ、rescueという参照で保護します。', 'featureの不在、rescueのc2、app.tsのFeatureを確認します。', 'ブランチ名を消すことと、コミット内容の即時消去は別です。実Gitの記録には期限があります。'),
  'workflow-revert': note('共有済みBugの変更だけを逆向きに記録し、後のUseful docsを残して公開します。', '親c3の取り消しコミットと、手元・サーバーのアプリと文書内容を確認します。', '共有履歴をresetで置き換えず、取り消しの理由を新しい履歴として残す方法です。'),
  'workflow-release': note('リリース時点から保守修正を作り、タグを共有し、mainにも同じ修正を移植します。', 'maintenanceとmainのFixed、v1.0.1の参照・注釈・公開状態を確認します。', 'タグの共有とmainのpushは別です。修正を両系統へ反映したことを確認します。'),
  'daily-status': note('app.ts、README.md、notes.txtは異なる場所に変更があります。未追跡と、追跡済みの未ステージ・ステージ済みを区別します。', 'statusの分類と三つの対象を照らし合わせます。', 'statusはファイルの内容を変えません。調べる課題は確認操作の成功を採点します。'),
  'daily-diff': note('まだ選んでいないapp.tsの編集は、作業ツリーとindexの差として現れます。', 'diffでversion 1からversion 2への変更を読みます。', '通常のdiffはHEADと作業ツリーの全差分ではありません。ステージ済みの差は別に確認します。'),
  'daily-staged-diff': note('app.tsのversion 2を選んだ後のversion 3は、今回のindexには入りません。', 'ステージ済み差分でversion 2が対象と分かることを確認します。', 'この課題はindex対HEADの確認です。通常のdiffだけでは違う領域を見ます。'),
  'daily-select': note('app.tsだけを選べば、README.mdのDraftを作業中のまま残せます。', 'HEADのREADME.mdがProject、作業ツリーではDraftであることを確認します。', 'add .でREADME.mdまで選ぶと、今回の記録範囲が広がります。'),
  'daily-after-stage': note('commitはindexのversion 2を記録し、後のversion 3は未記録で残ります。', 'HEADと作業ツリーのapp.tsを比べ、異なる二つの版が残ることを確認します。', '再度addするとversion 3へ選び直します。この課題では選び直す必要がありません。'),
  'daily-unstage': note('ステージの解除はindexを戻す操作です。作業ツリーのversion 2は残します。', 'indexがversion 1で、作業ファイルがversion 2のままであることを確認します。', '作業ツリーを戻すrestoreと、indexを戻すrestore --stagedを区別します。'),
  'daily-restore': note('未ステージの試行を捨て、app.tsを記録されたversion 1へ戻します。', 'プレビューとstatusで追跡ファイルに差がなくなったことを確認します。', 'restoreで消した未記録の編集は、コミットの履歴から復旧できるとは限りません。'),
  'daily-restore-index': note('通常のrestoreの戻し元はindexです。今回はステージ済みversion 2を残して作業内容も合わせます。', '作業ツリーとindexがともにversion 2であることを確認します。', 'HEADはversion 1のままです。編集がないことと、コミット済みであることは別です。'),
  'daily-delete': note('作業ファイルを消すだけでなく、README.mdの削除を履歴へ記録します。', 'コミットにREADME.mdがなく、メッセージがRemove READMEであることを確認します。', 'この課題はメッセージも指定しています。過去のコミットの内容は削除されません。'),
  'daily-move': note('app.tsの内容をmain.tsへ移し、元のパスの削除と新しいパスの追加を記録します。', 'HEADと作業ツリーでapp.tsがなく、main.tsがversion 1であることを確認します。', '実Gitのrename表示は内容の類似性から判断されます。ファイル内容を保つことが大切です。'),
  'daily-amend-message': note('amendは新しい親を追加する代わりに、直前コミットを作り直します。', '親が増えず、内容を保ってメッセージがClarify setupになったことを確認します。', 'IDが変わるので、共有済みの履歴の書き換えはチームの合意が必要です。'),
  'daily-amend-file': note('追加漏れをindexへ選び、直前の記録を内容だけ補って作り直します。', '親とメッセージを保ち、HEADのREADME.mdがUpdatedであることを確認します。', 'amend --no-editはメッセージを保ちます。作業ツリーを編集しただけでは追加されません。'),
  'daily-switch': note('feature/loginという参照を作り、そのブランチへ作業先を移します。', 'HEADとブランチ名がfeature/loginであることを確認します。', '作成済みの同名ブランチは新規作成できません。作成と移動を分ける別解もあります。'),
  'daily-split': note('app.tsとREADME.mdを別々に選び、目的の異なる変更を二つのコミットに分けます。', '各コミットの内容と、最後からUpdate docs、Update appの順を確認します。', '二つのメッセージだけでは分割を証明できません。最初のコミットに文書変更を混ぜないことを確認します。'),
  'github-create': note('公開したfeature/loginの変更をmainへ提案します。PRはブランチの統合前の相談と確認の場です。', 'PRのhead、base、タイトルAdd loginと空でない説明を確認します。', 'ghはGitHub CLI、simulateはアプリ専用です。この課題では実アカウントや通信を使いません。'),
  'github-view': note('PRの状態を読むと、どの変更をどこへ取り込み、何が確認待ちか分かります。', 'PR #1のタイトル、本文、統合先、レビュー、CIを読みます。', 'viewは承認やマージを行いません。模擬レビューと模擬CIは実サービスではありません。'),
  'github-review-feedback': note('修正依頼は未承認の状態です。求められた内容を読んでから更新する必要があります。', 'PR #1を表示し、最新コミットへのchanges_requestedと依頼文を確認します。', 'simulateでレビュアーの反応を再現します。実GitHubではレビュアーが投稿します。'),
  'github-ci-failure': note('CIの失敗は、現在の公開コミットに対する確認が通っていない状態です。', 'PR #1のチェック結果でfailureを確認します。', 'simulateは失敗結果を設定するだけです。実際のテストやジョブを実行しません。'),
  'github-approval': note('承認は、レビューした公開コミットに対して有効です。後の変更まで承認したことにはなりません。', 'PR #1のreviewが最新の公開コミットへのapprovedであることを確認します。', '修正をpushすると、このアプリでは以前の承認だけでmergeできません。'),
  'github-ci-success': note('CI成功は、確認した公開コミットに結び付きます。成功後の新しい変更は再確認が必要です。', 'PR #1のチェック結果で最新コミットへのsuccessを確認します。', '模擬CIの成功は、実際のコード品質を保証しません。実サービスではジョブ内容を読む必要があります。'),
  'github-merge': note('最新変更への承認とCI成功を揃えてから、mainへ提案を取り込みます。', 'PRがmergedで、模擬サーバーのmainにapp.tsのversion 2があることを確認します。', 'この模擬PRはmerge方式を扱います。squash/rebase方式や実GitHubへの接続は含みません。'),
  'github-close': note('closeは提案を終了し、mainへは変更を取り込みません。', 'PRがclosedで、mainのapp.tsがversion 1のままであることを確認します。', 'closeとmergeは別の結果です。不要な提案を閉じてもブランチの履歴は残ります。'),
  'github-review-fix': note('修正したversion 3を公開すると、以前のレビューやCI結果では確認が足りません。', '更新後の公開コミットへの承認とCI成功、mainのversion 3を確認します。', '手元のcommitだけではPRは更新されません。push先と最新コミットの対応を確認します。'),
  'remote-clone': note('cloneは共有履歴を取得して、ローカルの作業場所と追跡先を準備します。', 'mainのc2、app.tsのversion 2、origin/mainへの追跡設定を確認します。', 'mock://は仮想URLで外部通信しません。実Gitのcloneは別ディレクトリを作ります。'),
  'remote-list': note('fetchとpushで使う接続先を調べると、誤った送信先を避けられます。', 'remote -vのURLと、fetch/pushの用途を読みます。', 'この演習のURLは模擬接続先です。ホストのGit設定には影響しません。'),
  'remote-add': note('接続先の名前originとURLを登録します。登録しただけでは履歴を取得しません。', 'originのURLがmock://team/projectになったことを確認します。', '実務ではリポジトリのURLと権限を確認します。このアプリは仮想接続先だけを扱います。'),
  'remote-url': note('接続先の名前を保ったまま、移転先へURLだけを更新します。', 'originのURLがmock://team/new-projectであることを確認します。', 'URLの変更と追跡参照の更新は別です。変更しただけで新しいコミットは取得しません。'),
  'remote-fetch': note('fetchは手元の追跡参照を更新します。現在のブランチと作業ファイルは統合せず保ちます。', 'origin/mainがc2、ローカルHEADがc1、app.tsがversion 1であることを確認します。', '追跡参照、ローカルブランチ、サーバーのブランチを同じものとして扱わないでください。'),
  'remote-pull': note('取得した更新をmainへfast-forwardし、作業ファイルも最新にします。', 'HEADがc2で、app.tsがversion 2、追跡ファイルがクリーンであることを確認します。', '--ff-onlyは分岐していると拒否します。意図しないマージを防ぐ使い方です。'),
  'remote-first-push': note('初回pushで履歴を共有し、今後の送受信先としてorigin/mainを設定します。', '模擬サーバーのmainがc1で、upstreamがorigin/mainであることを確認します。', 'pushの成功と追跡設定は別の条件です。-uで両方を設定できます。'),
  'remote-push': note('ローカルで記録した文書の変更を、模擬サーバーのmainへ送ります。', 'サーバーのmainがc3を指し、README.mdがLocal docsであることを確認します。', '作業ツリーの編集はpushされません。コミットした履歴が送信対象です。'),
  'remote-integrate': note('分岐した履歴は、他メンバーの変更を取得し統合してから共有します。', '手元とサーバーの両方にapp.tsとREADME.mdの必要な内容があることを確認します。', '強制pushで片方を消す目的ではありません。相手の履歴を確認して統合します。'),
  'remote-rebase': note('ローカルの文書変更を最新のチーム変更の後へ載せ替え、直線の履歴にします。', 'Local docs、Team update、Initialの順と、サーバーに双方の内容があることを確認します。', 'rebaseはコミットIDを変えます。既に共有した履歴を書き換えるときは合意が必要です。'),
  'remote-prune': note('サーバーで消えたブランチの追跡参照を整理し、古い情報を残さないようにします。', 'origin/obsoleteが消え、ローカルmainはc1のままであることを確認します。', 'pruneはローカルの同名ブランチを削除する操作ではありません。'),
  'remote-remove': note('接続先の登録と、その接続先に属する追跡参照を取り除きます。', 'originとorigin/mainがなくなったことを確認します。', '実際のサーバーのリポジトリを消す操作ではありません。ローカル履歴は別に残ります。'),
  'history-graph': note('親子とブランチ参照をまとめて読むと、mainとfeatureの分岐点が分かります。', '一行メッセージと全ブランチのグラフで共通の親を確認します。', '--allは他の参照も含めます。通常のlogは現在のHEAD側をたどります。'),
  'history-show': note('特定コミットのメッセージと変更を読むと、何を導入したかを調べられます。', 'c2のFeatureメッセージとapp.tsの差分を読みます。', 'showは作業ファイルを過去へ切り替えません。'),
  'history-show-file': note('コミットとパスを指定して、その時点のファイル内容だけを読みます。', 'c1時点のapp.tsを読み、現在の作業内容が変わらないことを確認します。', 'c1:app.tsの区切りはコロンです。このアプリのc1は教材用のIDです。'),
  'history-config': note('コミットの作者情報を模擬リポジトリ内に設定します。', 'user.nameがLearner、user.emailがlearner@example.testであることを確認します。', '設定はブラウザ内だけです。実Gitにはlocal/global/systemの設定範囲があります。'),
  'history-rename-branch': note('参照の名前を変えても、指しているコミットと履歴は変わりません。', 'featureが消え、feature/loginがc2を指すことを確認します。', 'ローカルの名前変更だけでは、サーバー側のブランチ名は変更されません。'),
  'history-delete-branch': note('mainへ統合したfeatureの名前を整理します。残す履歴はmainが参照しています。', 'HEADがmainで、featureがなく、mainがc2を指すことを確認します。', '-dは未統合の履歴を守ります。強制削除の-Dとは条件が異なります。'),
  'history-detached-rescue': note('直接選んだc2へrescueという名前を付け、後から履歴を見つけられるようにします。', 'HEADがrescueを指し、app.tsがversion 2であることを確認します。', 'Detached HEADで作ったコミットを残す場合も、離れる前に参照を作ります。'),
  'history-no-ff': note('fast-forwardできる状況でも、統合を二親のコミットとして記録します。', '新しいコミットの親がc1とc2で、app.tsがversion 2であることを確認します。', '--no-ffは履歴の見せ方を変えます。常に必要な方式ではなく、チームの方針に合わせます。'),
  'history-rebase': note('featureの変更をmainの文書変更の後へ載せ替えます。', 'featureの最新コミットの親がc3で、アプリと文書の変更が残ることを確認します。', 'rebase後はコミットIDが変わります。共有済みの履歴では他の利用者への影響を確認します。'),
  'history-pick': note('c2の変更だけを現在のmainへ移植し、mainの文書変更を保ちます。', '親がc3で、Featureの内容とDocumentationが共存することを確認します。', 'cherry-pickはブランチ全体の統合ではありません。同じ変更の二重適用にも注意します。'),
  'history-revert': note('後続の文書を残したまま、c2のアプリ変更を逆向きの新しいコミットで取り消します。', '元の履歴を親に持つ取り消しコミットと、文書が残ることを確認します。', 'resetと違って履歴を消しません。後の変更と競合する場合は内容の判断が必要です。'),
  'history-reflog': note('reflogはローカルでHEADが移動した記録です。履歴の親とは別の順でたどります。', 'reset前のHEADがc2だったことを読みます。', '実Gitのreflogには保存期間があり、他の端末の記録は共有されません。'),
  'history-recover-reset': note('resetで参照から外れた記録も、reflogで見つけてrescueへ保護できます。', 'mainがc1、rescueがc2で、元のapp.tsが戻ることを確認します。', 'reflogで救えるのは主にコミット済みの内容です。未コミット編集の復元を保証しません。'),
  'history-tag': note('タグはリリース等の特定コミットに付ける参照です。', 'v1.0.0がmainのc3を指すことを確認します。', 'ブランチと異なり、タグは通常、新しいコミットを作っても進めません。'),
  'history-annotated-tag': note('注釈付きタグは、参照先だけでなくリリース説明も持ちます。', 'v1.1.0がc3で、注釈がRelease 1.1.0であることを確認します。', 'この模擬環境は署名やタグオブジェクト全体を再現しません。'),
  'history-tag-branch': note('v1.0.0の状態からmaintenanceを作り、当時の内容で保守を始めます。', 'HEADがmaintenanceのc1で、app.tsがversion 1であることを確認します。', 'タグを移動する代わりに、新しいブランチで保守の履歴を伸ばします。'),
  'level-1-1': note('初期化は、この作業場所で履歴を管理するための準備です。ファイル作成やコミットとは別の段階です。', '初期化の成功メッセージと、まだコミットがないことを確認します。', '実Gitはディスクに.gitを作ります。このアプリはブラウザ内の状態を初期化します。'),
  'level-1-2': note('README.mdを作っただけでは履歴に入りません。作業ツリー、index、履歴の三段階を区別します。', 'ファイル一覧でREADME.mdの存在を、statusで未追跡の表示を確認します。', '空ファイルも管理できます。touchとechoは、このアプリで使える簡易ファイル操作です。'),
  'level-1-3': note('未追跡は、まだ次のコミットへ選ばれていない新しいファイルです。statusは内容を変更せず状態を調べます。', 'README.mdがUntracked filesにあることを読みます。', 'この演習はstatusの実行を採点します。出力を理解したかの自動判定は行いません。'),
  'level-1-4': note('ステージングは、README.mdの現在の内容を次のコミットに選ぶ操作です。まだ履歴には入りません。', 'statusでステージ済みになり、indexとHEADに差があることを確認します。', 'add .は他の変更も含めます。実務では対象ファイルと差分を確認してから記録します。'),
  'level-1-5': note('コミットはindexに選んだ内容を履歴へ記録します。この演習ではREADME.mdが既にステージされています。', 'logに最初のコミットが現れ、README.mdが記録されていることを確認します。', 'メッセージだけを入力しても、必要な内容がindexになければ記録できません。'),
  'level-1-6': note('logは現在のHEADから親コミットをたどります。ファイル一覧では分からない変更の記録を読む操作です。', 'コミットID、メッセージ、親子の順を読み、最初のコミットを確認します。', 'この演習は確認操作を採点します。作者や日時は模擬情報です。'),
  'level-1-7': note('README.mdの作業内容とHEADの記録が異なると、編集が未記録の変更として残ります。', 'プレビューとdiffでREADME.mdの変更を確認します。', 'echoの > は上書きです。実シェルの追記 >> はこのアプリでは未対応です。touchは既存ファイルの内容を変更しません。'),
  'level-1-8': note('通常のdiffはindexと作業ツリーの差を示します。まだステージしていない編集を調べます。', 'README.mdの削除行と追加行を読みます。', 'ステージ後の内容を見るときはdiff --stagedを使います。この課題は未ステージ差分を調べます。'),
  'level-1-9': note('再編集したREADME.mdをindexへ選び直してから、二つ目のコミットへ記録します。', 'logの親子と、HEADのREADME.mdが作業内容と一致することを確認します。', '前回のaddは、その時点の内容を選びます。後の編集まで自動でコミットされません。'),
  'level-1-10': note('app.tsを作り、次のコミットへ選び、履歴に記録する一連の操作です。', '作業ファイルの存在だけでなく、HEADのコミットにapp.tsがあることを確認します。', '別のファイルをコミットしても、この課題の対象を記録したことにはなりません。'),
  'level-2-1': note('ブランチは現在のコミットを指す名前です。名前を作ることと、作業先を移すことは別です。', 'グラフでfeatureという参照が現れることを確認します。', '作成だけの操作と、作成して移動する操作の両方を利用できます。'),
  'level-2-2': note('作業先をfeatureへ切り替えると、HEADはfeatureブランチを指します。', 'グラフのfeatureにHEADが付いていることを確認します。', '実務では切り替え前にstatusを確認し、移動先と衝突する未記録変更を保護します。'),
  'level-2-3': note('featureで作業ファイルを作ります。ブランチ上の記録は、後でコミットして初めて分岐します。', 'featureにHEADがあり、feature.txtが作業ツリーにあることを確認します。', 'mainへ移動してファイルを作ると、指定した作業場所での練習になりません。'),
  'level-2-4': note('feature.txtをfeatureの履歴へ記録すると、featureの参照だけが先へ進みます。', 'feature側のHEADにfeature.txtがあり、mainの参照が元の位置にあることを確認します。', '関係のないファイルのコミットやmainでのコミットでは、この目的を満たしません。'),
  'level-2-5': note('mainへ戻ると、mainのコミットに記録されたファイルへ作業内容が切り替わります。', 'HEADがmainへ移り、feature側の履歴は残っていることを確認します。', 'ブランチの移動はfeatureのコミットを削除する操作ではありません。'),
  'level-2-6': note('ブランチごとのファイルは、そのブランチが指すコミットの内容で決まります。', '一覧を読み、mainにはfeature.txtがないことを確認します。', 'この演習ではファイル一覧を確認する操作を採点します。各演習の初期状態は独立しています。'),
  'level-2-7': note('main側でmain.txtを作ります。featureの変更と別の仕事を履歴へ残す準備です。', 'HEADがmainで、main.txtが作業ツリーにあることを確認します。', '作成したファイルはまだ未追跡です。次のコミットへ含めるにはステージが必要です。'),
  'level-2-8': note('main.txtをmainへ記録すると、featureとmainの両方に独自のコミットができ、履歴が分岐します。', 'mainの最新コミットにmain.txtがあり、featureの参照を保持していることを確認します。', 'コミット数だけでなく、記録した対象と作業ブランチを確認します。'),
  'level-2-9': note('履歴の分岐は、二つの参照が共通の親から別のコミットへ進んだ状態です。', 'グラフのmainとfeatureの位置、共通の親を読みます。', '通常のlogは現在のHEAD側をたどります。全ブランチ表示では--allを使います。'),
  'level-3-1': note('mergeは現在のブランチへ相手の履歴を取り込みます。最初に統合先を確認します。', 'HEADがmainにあることを確認します。', '逆のブランチでmergeすると統合先が変わります。ブランチ名と作業内容を確認します。'),
  'level-3-2': note('mainがfeatureの祖先なら、mainの参照を進めるだけで履歴を統合できます。', 'mainの参照がfeatureと同じc2へ進んだことを確認します。', 'fast-forwardでは新しい二親のコミットは作りません。分岐した履歴とは異なります。'),
  'level-3-3': note('feature2を作って独自の変更を記録し、次の履歴分岐を準備します。', 'HEADがfeature2で、feature2.txtがそのコミットにあることを確認します。', 'mainに同じ変更を記録すると、この課題で準備する分岐の形になりません。'),
  'level-3-4': note('mainにも別のコミットを作ると、feature2を参照移動だけでは取り込めなくなります。', 'main-update.txtとメッセージUpdate main、HEADがmainであることを確認します。', 'この課題は指定メッセージも採点します。実務のメッセージは変更目的を説明します。'),
  'level-3-5': note('分岐したmainとfeature2を統合すると、双方を親に持つマージコミットを作ります。', 'mainの最新コミットの二つの親と、双方のファイル内容を確認します。', '別のブランチとの二親コミットを作っただけでは、feature2の統合にはなりません。'),
  'level-4-1': note('退避前に、編集が作業ツリーとindexのどこにあるかを調べます。', 'statusでREADME.mdの未記録変更を読みます。', 'stashが必要かを判断するため、まず対象と変更範囲を確認します。'),
  'level-4-2': note('stashは作業中の変更を一時保管し、追跡ファイルをHEADの内容へ戻します。', 'statusで追跡ファイルがクリーンになり、stash listに一件あることを確認します。', '通常のstashは未追跡ファイルを含みません。必要な場合は-uを検討します。'),
  'level-4-3': note('stashの一覧を読み、どの作業をどの順序で保管したか確認します。', 'stash@{0}が最新の保管であることを確認します。', '一覧の番号は削除や追加で変わります。実務では適用前に内容も確認します。'),
  'level-4-4': note('保管したREADME.mdの編集を作業ツリーへ戻します。適用と保管の削除を区別します。', 'プレビューとdiffでREADME.mdの編集が戻ったことを確認します。', 'applyは保管を残し、成功したpopは消します。この演習は復元した内容を採点します。'),
  'level-5-1': note('取り消す前に、どのコミットが間違いかを履歴で確認します。', 'logで最新コミットと一つ前のコミットを読みます。', '共有済みの履歴を戻す場合は、resetによる書き換えとrevertによる追加を区別します。'),
  'level-5-2': note('soft resetはHEADだけを戻し、indexと作業ツリーの内容を残します。', 'HEADがc1へ戻り、error.txtがindexと作業ツリーに残ることを確認します。', '実務で共有済みブランチをresetする場合は、他の利用者への影響を確認します。'),
  'level-5-3': note('コミットを戻した後、不要なerror.txtをindexと作業ツリーから除いて記録し直します。', 'HEADにerror.txtがなく、メッセージがCorrect commitであることを確認します。', '作業ファイルの削除だけではindexに残ることがあります。コミット対象も確認します。'),
  'level-5-4': note('hard resetはHEAD、index、追跡ファイルを指定コミットの内容へ戻します。', 'HEADがc1、追跡ファイルがクリーンで、bad.txtがなくなったことを確認します。', '未コミットの追跡ファイルの変更は失われます。無関係な未追跡ファイルをすべて削除する操作ではありません。'),
  'level-6-1': note('過去を調べる前に、戻りたいコミットのIDを履歴から特定します。', 'logでコミットの順とc1の位置を確認します。', 'このアプリのc1等は教材用IDです。実Gitはハッシュを使います。'),
  'level-6-2': note('コミットを直接選ぶと、HEADはブランチ名ではなくコミットを指します。', 'HEADが直接c1を指し、Detached HEADになっていることを確認します。', 'ここで作ったコミットを残すには、離れる前にブランチを作ります。'),
  'level-6-3': note('名前のあるmainへ戻ると、HEADは再びブランチを指します。', 'HEADがmainへ戻り、mainの作業内容になったことを確認します。', 'Detached HEADで新しい記録を作った場合、必要な履歴を先にブランチで保護します。'),
  'level-7-1': note('mainとfeatureの変更を自動で決められないと、mergeは競合で停止します。', 'マーカー、ファイル一覧、操作中の状態で競合の発生を確認します。', 'この課題では競合による意図した停止が達成です。模擬エンジンの競合判定は主にファイル単位です。'),
  'level-7-2': note('競合中は通常の変更とは違い、統合結果をまだ決めていない状態です。', 'statusのunmerged表示と、対象index.htmlを確認します。', '競合の発生と、解消してstageした状態は別です。'),
  'level-7-3': note('競合した見出しを選び、HTML全体を保って解消します。マーカーを消すだけでは不十分です。', 'index.htmlのプレビューでHTML構造と必要な見出しを確認します。', '現在側、取り込み側、両方がこの教材の許容結果です。両方を採用しても一般のコードが正しく動く保証はありません。'),
  'level-7-4': note('解消したindex.htmlをstageし、双方の親を持つコミットとしてmergeを終えます。', 'mainの最新コミットの親、index.htmlの内容、merge終了を確認します。', '解消内容の適用だけではmergeは終わりません。このアプリではadd後にcommitで完了します。'),
};
